// ============================================================================
// IMPORTS
// ============================================================================

import { app, Menu, nativeImage, Tray } from 'electron'
import type { BrowserWindow, NativeImage } from 'electron'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { IPC_CHANNELS } from './types.js'
import { APP_NAME } from '../../src/constants/app.constants.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

type GetWindow = () => BrowserWindow | null

// ============================================================================
// STATE
// ============================================================================

let tray: Tray | null = null
let _getWindow: GetWindow | null = null
let _isRunning = false
let _mode = 'basic'
let _screenLock = false
let _shutdown = false

// ============================================================================
// CONSTANTS — Tray icon PNG filenames
// ============================================================================

// Pre-generated by `npm run generate:icons` (scripts/generate-app-icon.mjs).
// Green bg = running state, red bg = stopped state.
// The @2x variants are picked up automatically by Electron on retina displays.
const TRAY_FILE_RUNNING = 'tray-running.png'
const TRAY_FILE_STOPPED = 'tray-stopped.png'

// ============================================================================
// UTILITY FUNCTIONS — Icon loader
// ============================================================================

/**
 * Resolve the absolute path to a tray icon PNG by searching the same
 * candidate directories used by getAppIcon() — packaged resourcesPath first,
 * then dev-mode project root and Vite build output.
 */
function resolveTrayIconPath(filename: string): string | null {
  const resourcesPath = (process as NodeJS.Process & { resourcesPath?: string }).resourcesPath

  const candidates: string[] = []

  if (resourcesPath) {
    candidates.push(path.join(resourcesPath, 'resources', filename))
  }

  candidates.push(
    path.join(process.cwd(), 'resources', filename),
    path.join(__dirname, 'resources', filename),
    path.join(__dirname, '../resources', filename),
  )

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

/**
 * Load the pre-generated tray PNG for the given running state.
 *
 * Electron automatically picks up the `@2x` sibling file for retina/high-DPI
 * displays when `createFromPath()` is used and the `@2x` file exists in the
 * same directory.
 *
 * Falls back to a plain solid-colour rounded-rect bitmap when the PNG files
 * have not been generated yet (e.g. a fresh clone before the first build).
 */
function buildTrayIcon(isRunning: boolean): NativeImage {
  const filename = isRunning ? TRAY_FILE_RUNNING : TRAY_FILE_STOPPED
  const pngPath = resolveTrayIconPath(filename)

  if (pngPath) {
    try {
      const img = nativeImage.createFromPath(pngPath)
      if (!img.isEmpty()) return img
    } catch {
      // fall through to bitmap fallback
    }
  }

  // ── Fallback: 32×32 solid-colour rounded-rect (BGRA) ─────────────────────
  // Used only when PNG assets have not been generated yet.
  // Running: #2d6a4f → BGRA [79, 106, 45]  |  Stopped: #9b2335 → BGRA [53, 35, 155]
  const SIZE = 32
  const R = 6
  const buf = Buffer.alloc(SIZE * SIZE * 4, 0)
  const [b, g, r] = isRunning ? [79, 106, 45] : [53, 35, 155]
  const cx = (SIZE - 1) / 2
  const cy = (SIZE - 1) / 2

  for (let y = 0; y < SIZE; y++) {
    for (let x = 0; x < SIZE; x++) {
      const rx = Math.max(0, Math.abs(x - cx) - (cx - R))
      const ry = Math.max(0, Math.abs(y - cy) - (cy - R))
      if (rx * rx + ry * ry <= R * R) {
        const i = (y * SIZE + x) * 4
        buf[i] = b; buf[i + 1] = g; buf[i + 2] = r; buf[i + 3] = 255
      }
    }
  }
  return nativeImage.createFromBitmap(buf, { width: SIZE, height: SIZE })
}

// ============================================================================
// UTILITY FUNCTIONS — Menu builder
// ============================================================================

function buildContextMenu(getWindow: GetWindow): Menu {
  const statusLabel = _isRunning ? '● Running' : '○ Stopped'
  const modeLabel   = `Mode: ${_mode === 'advanced' ? 'Advanced' : 'Basic'}`

  const sendPreset = (hours: number) => {
    const win = getWindow()
    if (!win) return
    win.show()
    win.focus()
    win.webContents.send(IPC_CHANNELS.TRAY_REQUEST_START_PRESET, { hours })
  }

  return Menu.buildFromTemplate([
    { label: statusLabel, enabled: false },
    { type: 'separator' },
    {
      label: 'Start Automation',
      enabled: !_isRunning,
      click: () => {
        const win = getWindow()
        if (win) {
          win.show()
          win.focus()
          win.webContents.send(IPC_CHANNELS.TRAY_REQUEST_START)
        }
      },
    },
    {
      label: 'Quick Start',
      enabled: !_isRunning,
      submenu: [
        { label: 'Start for 1 hour',  click: () => sendPreset(1) },
        { label: 'Start for 2 hours', click: () => sendPreset(2) },
        { label: 'Start for 3 hours', click: () => sendPreset(3) },
        { label: 'Start for 4 hours', click: () => sendPreset(4) },
      ],
    },
    {
      label: 'Stop Automation',
      enabled: _isRunning,
      click: () => {
        getWindow()?.webContents.send(IPC_CHANNELS.TRAY_REQUEST_STOP)
      },
    },
    { type: 'separator' },
    { label: 'After Timer Ends', enabled: false },
    {
      label: 'Screen Lock',
      type: 'checkbox',
      checked: _screenLock,
      enabled: !_isRunning,
      click: () => {
        const next = !_screenLock
        getWindow()?.webContents.send(IPC_CHANNELS.TRAY_SET_SCREEN_LOCK, { value: next })
      },
    },
    {
      label: 'Shutdown',
      type: 'checkbox',
      checked: _shutdown,
      // Shutdown can only be toggled once Screen Lock is enabled.
      enabled: !_isRunning && _screenLock,
      click: () => {
        const next = !_shutdown
        getWindow()?.webContents.send(IPC_CHANNELS.TRAY_SET_SHUTDOWN, { value: next })
      },
    },
    { type: 'separator' },
    { label: modeLabel, enabled: false },
    { type: 'separator' },
    {
      label: 'Open Application',
      click: () => {
        const win = getWindow()
        if (win) { win.show(); win.focus() }
      },
    },
    { type: 'separator' },
    { label: 'Exit', click: () => app.quit() },
  ])
}

// ============================================================================
// EXPORTS
// ============================================================================

/**
 * Create the system tray icon and context menu.
 * Must be called after app.whenReady().
 */
export function createTray(getWindow: GetWindow): void {
  _getWindow = getWindow
  tray = new Tray(buildTrayIcon(false))
  tray.setToolTip(`${APP_NAME} — Stopped`)
  tray.setContextMenu(buildContextMenu(getWindow))

  tray.on('double-click', () => {
    const win = getWindow()
    if (win) { win.show(); win.focus() }
  })
}

/**
 * Sync tray icon and menu with the current automation running state.
 * Called from ipc.ts on every automation:status change.
 */
export function updateTrayStatus(isRunning: boolean): void {
  if (!tray || !_getWindow) return
  _isRunning = isRunning
  tray.setImage(buildTrayIcon(isRunning))
  tray.setToolTip(`${APP_NAME} — ${isRunning ? 'Running' : 'Stopped'}`)
  tray.setContextMenu(buildContextMenu(_getWindow))
}

/**
 * Refresh the mode label in the tray context menu.
 * Called from ipc.ts when the renderer sends app:mode-changed.
 */
export function updateTrayMode(mode: string): void {
  if (!tray || !_getWindow) return
  _mode = mode
  tray.setContextMenu(buildContextMenu(_getWindow))
}

/**
 * Sync the After Timer Ends checkboxes in the tray menu with renderer state.
 * Called from ipc.ts when the renderer sends tray:post-stop-options-changed.
 */
export function updateTrayPostStopOptions(screenLock: boolean, shutdown: boolean): void {
  if (!tray || !_getWindow) return
  _screenLock = screenLock
  _shutdown = shutdown
  tray.setContextMenu(buildContextMenu(_getWindow))
}

/** Destroy the tray on app exit. */
export function destroyTray(): void {
  tray?.destroy()
  tray = null
}
